# Generated by Django 4.1.3 on 2022-11-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('NOR', 'Normal'), ('FIR', 'Fire'), ('WAT', 'Water'), ('ELE', 'Electric'), ('GRA', 'Grass'), ('ICE', 'Ice'), ('FIG', 'Fighting'), ('POI', 'Poison'), ('GRO', 'Ground'), ('FLY', 'Flying'), ('BUG', 'Bug'), ('ROC', 'Rock'), ('GHO', 'Ghost'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('STE', 'Steel'), ('FAI', 'Fairy')], default='NOR', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='move',
            name='movename',
            field=models.CharField(max_length=25, verbose_name='Move Name'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weaknesses',
            field=models.ManyToManyField(to='main_app.weakness'),
        ),
    ]
