# Generated by Django 4.1.3 on 2022-11-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_weakness_alter_move_movename_pokemon_weaknesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weakness',
            name='element',
            field=models.CharField(max_length=15),
        ),
    ]
